DROP DATABASE IF EXISTS SALAODB;
CREATE DATABASE SALAODB;
USE SALAODB;

CREATE TABLE CLIENTE(
IDCLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,NOME VARCHAR (255) NOT NULL
,SOBRENOME VARCHAR(255) NOT NULL
,TELEFONE  VARCHAR(14) NOT NULL
,CPF VARCHAR (16) NOT NULL
, OBSERVACAO VARCHAR (255) NOT NULL
);

CREATE TABLE ESPECIALIDADE(
IDESPECIALIDADE INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,NOME VARCHAR(255) NOT NULL
);

CREATE TABLE SERVICO(
IDSERVICO INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,SERVICO VARCHAR(255) NOT NULL
);


CREATE TABLE PROFISSIONAL(
IDPROFISSIONAL INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,NOME VARCHAR(255) NOT NULL
,ESPECIALIDADE VARCHAR(255) NOT NULL
);

CREATE TABLE SERVICO_TEM_ESPECIALIDADE(
IDESPECIALIDADE INT NOT NULL AUTO_INCREMENT
,IDSERVICO INT NOT NULL
, FOREIGN KEY(IDESPECIALIDADE) REFERENCES ESPECIALIDADE (IDESPECIALIDADE)
, FOREIGN KEY(IDSERVICO) REFERENCES SERVICO (IDSERVICO)
);

CREATE TABLE AGENDAMENTO(
IDAGENDAMENTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,IDCLIENTE INT NOT NULL
,IDPROFISSIONAL INT NOT NULL
,IDSERVICO INT NOT NULL
,DATACOMHORA TIMESTAMP NOT NULL
,VALOR DOUBLE NOT NULL

, FOREIGN KEY(IDSERVICO) REFERENCES SERVICO (IDSERVICO)
, FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
, FOREIGN KEY(IDPROFISSIONAL) REFERENCES PROFISSIONAL (IDPROFISSIONAL)
);

insert into PROFISSIONAL (IDPROFISSIONAL,ESPECIALIDADE, NOME) values (2,'CABELEREIRA','MIRIAM');
insert into PROFISSIONAL (IDPROFISSIONAL,ESPECIALIDADE, NOME) values (3,'CABELEREIRA','SABRINA');
insert into PROFISSIONAL (IDPROFISSIONAL,ESPECIALIDADE, NOME) values (4,'MANICURE','JOICE');

insert into SERVICO (IDSERVICO, SERVICO) values (1,'CORTE');
insert into SERVICO (IDSERVICO, SERVICO) values (2,'ESCOVA');
insert into SERVICO (IDSERVICO, SERVICO) values (3,'PROGRESSIVA');
insert into SERVICO (IDSERVICO, SERVICO) values (4,'PENTEADO');
insert into SERVICO (IDSERVICO, SERVICO) values (5,'HIDRATAÇÃO');
insert into SERVICO (IDSERVICO, SERVICO) values (6,'ALISAMENTO');
insert into SERVICO (IDSERVICO, SERVICO) values (7,'MANICURE');
insert into SERVICO (IDSERVICO, SERVICO) values (8,'MANICURE COM FRANCESINHA');
insert into SERVICO (IDSERVICO, SERVICO) values (9,'PEDICURE');
insert into SERVICO (IDSERVICO, SERVICO) values (10,'PEDICURE COM FRANCESINHA');